# Generated by Django 5.0.4 on 2025-11-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table=None,
        ),
    ]
